### ISSUE TITLE
Possibility to move to module format?

### ISSUE THREAD

**Issue by Erisa** [Snazzah/slash-create-worker#4]
`slash-create-worker` currently uses the [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) format for Workers, which were what they launched with and worked well.

In late 2021, [Module format](https://blog.cloudflare.com/workers-javascript-modules/) was introduced.

Now, I am not an expert on the differences between the two except one is a Service Worker and one is a module, however more recent Cloudflare Developer Platform products like D1, Analytics Engine, Queues, etc. are all prioritising Module Format and do not well, if at all, on Service Worker format. While Service Workers are not yet deprecated, that does appear to be eventual plan.

So I was wondering, would it be possible to move slash-create-worker into a Module Format Worker?

Relevant doc: https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/

**Comment by avasilic** [comment]
+1
